# Generated by Django 5.1.6 on 2025-02-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите название заголовка", max_length=100, verbose_name="Заголовок"),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Введите текст статьи", null=True, verbose_name="Описание статьи"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото для статьи",
                        null=True,
                        upload_to="blogs/image",
                        verbose_name="Фото",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата публикации")),
                ("publication_sign", models.BooleanField(default=True, verbose_name="Публикация")),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0, help_text="Укажите количество просмотров", verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заголовок",
                "verbose_name_plural": "Заголовки",
                "ordering": ["title"],
            },
        ),
    ]
