# Generated by Django 5.1.6 on 2025-03-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_owner_product_status_publication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
